### ISSUE TITLE
Tool durability bar reset when exiting game with max durability multiplier set to large number

### ISSUE THREAD

**Issue by MoYiha** [Aidanamite/Misc-Cheats#1]
Hi, when I set `Tool Max Durability Multiplier` to 100000 (which effectively acts like infinite durability), I've noticed that when I exit the game and then re-enter, the durability bar for my tools resets to zero. However, the tools seem to function normally and have no actual limit on usage.

All Mods:
MiscCheats
modutils
extra-settings-api

Game Version: Latest

**Comment by Aidanamite** [comment]
i'm not at my pc rn, but iirc the game stores the durability differently between in-game and in the save files.

to be specfic, i thinl the game saves durability as a 16bit number rather than the 32bit number it uses while playing. so while playing, you can have durability up to about 2.47 billion, while the save files only allow up to 32,767.

you can check the exact remaining durability of the items using the statistic mod

**Comment by MoYiha** [comment]
You are correct. I've conducted multiple tests, and it indeed seems that durability values of 30000 or below are normal after exiting and re-entering the game, but values of 35000 and above reset to zero. 

However, there’s a special case with batteries. When I craft two batteries at the same time—one placed in the device and the other stored in a container—when I exit and re-enter the game, the one in the device remains normal, when I take the battery out of the device and check it in my inventory, it shows a durability of 50000, while the one stored in the container resets to zero.

**Comment by Aidanamite** [comment]
That's because the game saves battery slot contents differently to item slots. in the case of the batyery slots they use 32bit numbers

**Comment by Aidanamite** [comment]
That's because the game saves battery slot contents differently to item slots. in the case of the battery slots they use 32bit numbers

**Comment by MoYiha** [comment]
Thank you very much, your mods are very useful.
