### ISSUE TITLE
Issue with Building Hammer Stacking when "Boosted Stack Sizes" is Enabled

### ISSUE THREAD

**Issue by MoYiha** [Aidanamite/Misc-Cheats#2]
When the "Boosted Stack Sizes" is enabled, there is an issue with the stacking of the building hammer. Specifically, when placed in the inventory, multiple building hammers appear in a single slot.

**Comment by Aidanamite** [comment]
The stack size boosting was designed to boost all stacksizes other than tools that have durability because boosting them may have unwanted side-effects. so even items that normally can't stack like the empty bucket and building hammer, will become able to stack as there's no problem with them being able to stack
